# Stubs for deez.middleware (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from typing import Pattern

from deez.request import Request
from deez.response import Response


class Middleware:
    scoped: bool = ...

    def before_request(self, request: Request) -> Request: ...

    def before_response(self, response: Response) -> Response: ...

    @classmethod
    def run(cls, path: str) -> bool: ...


class ScopedMiddleware(Middleware):
    scoped: bool = ...
    path_regex: Pattern = ...
