# Stubs for deez.middleware (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from deez.request import Request
from deez.response import Response


class Middleware:
    def before_request(self, request: Request) -> Request: ...

    def before_response(self, response: Response) -> Response: ...
