# Stubs for deez.middleware (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Type

from stubs.deez.request import Request
from stubs.deez.resource import Resource
from stubs.deez.response import Response


class Middleware:
    resource: Type[Resource] = ...

    def __init__(self, resource: Type[Resource]) -> None: ...

    def before_request(self, request: Request) -> Request: ...

    def before_response(self, response: Response) -> Response: ...
