# Stubs for deez.middleware (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from stubs.deez.request import Request
from stubs.deez.resource import Resource
from stubs.deez.response import Response


class Middleware:
    resource: Resource = ...
    def __init__(self, resource: Resource) -> None: ...
    def before_request(self, request: Request) -> None: ...
    def before_response(self, response: Response) -> None: ...

class WildCardDomainResolverMiddleware(Middleware):
    def before_request(self, request: Request): ...
