# Stubs for deez.request (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

CAMELCASE_REGEX: Any

class Post:
    def __init__(self, body: Any) -> None: 
        self._data = None
        ...
    def get(self, key: Any): ...

    def _setup(self, body):
        pass


class Get:
    def __init__(self, params: Any) -> None: 
        self._data = None
        ...
    def get(self, key: str): ...

    def _setup(self, params):
        pass


class Request:
    lambda_context: Any = ...
    GET: Any = ...
    POST: Any = ...
    def __init__(self, event: Any, context: Any) -> None: ...
    def __dir__(self): ...
    def __getattr__(self, item: Any): ...
