# Stubs for deez.resource (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
from typing import Any, TypeVar

from stubs.deez.response import Response
from stubs.deez.request import Request

R = TypeVar('R', bound=Response)

class Resource:
    def dispatch(self, method: str = ..., request: Request = ..., *args: Any, **kwargs: Any) -> R: ...

    def get_class_name(self) -> str: ...

    def __str__(self) -> str: ...

    def _get_class_name(self) -> str: ...
