# Stubs for deez.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import List

def import_resolver(module_path: str) -> object: ...
def resolve_middleware_classes(middleware_classes: List[str]) -> List[object]: ...
