# Stubs for deez.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import List, Type

from deez.middleware import Middleware


def import_resolver(module_path: str): ...
def resolve_middleware_classes(middleware_classes: List[str]) -> List[Type[Middleware]]: ...
