# Stubs for deez.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import List, Type
from stubs.deez.middleware import Middleware

def import_resolver(module_path: str) -> Type[Middleware]: ...
def resolve_middleware_classes(middleware_classes: List[str]) -> List[Type[Middleware]]: ...
