# Stubs for deez.urls.parsers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List, Dict

UUID4_PATTERN: str
PATTERN_DETECTOR: Any
_alias_to_regex: Dict[str, str]


def find_patterns(value: str) -> List[str]: ...


def pattern_replacer(string: str) -> str: ...
