from typing import Any, Dict, List, Pattern, Union


class Setting:
    DEBUG: bool = ...
    MIDDLEWARE: List[Union[str, Dict[str, str]]] = ...
    CAMELCASE_REGEX: Pattern = ...
    EXCEPTION_HANDLER: str = ...
    LOGGER_MESSAGE_FORMAT: str = ...

    def __init__(self) -> None: ...

    def __getattr__(self, item: str) -> Any: ...

    def setup(self) -> None: ...

    def extend(self, *, configurations: Dict[str, Any]) -> None: ...

    def _reload(self) -> None: ...
