# Stubs for deez.conf.default_settings (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List

DEBUG: bool
MIDDLEWARE: List[str]
TEMPLATE_DIR: Any
