# Stubs for deez.urls (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional, Type

from deez.resource import Resource


class Path:
    regex: str = ...
    raw_url: str = ...
    resource: Type[Resource] = ...

    def __init__(self, regex: Any, resource: Type[Resource], raw_url: Optional[str] = None) -> None: ...

def path(url: str, resource: Type[Resource]) -> Path: ...
