# Stubs for deez.urls (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Type
from deez.resource import Resource


class Path:
    regex: str = ...
    resource: Type[Resource] = ...

    def __init__(self, regex: Any, resource: Any) -> None: ...

def path(url: str, resource: Type[Resource]) -> Path: ...

def path_resolver(url: str, resource: Type[Resource]) -> Path: ...

