# Stubs for deez.urls.parsers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import List


def find_patterns(value: str) -> List[str]: ...


def pattern_replacer(string: str) -> str: ...
