# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish to Gemfury

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.GEMFURY_PUSH_ONLY_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pipenv
        pipenv install --dev
        pipenv run python setup.py sdist bdist_wheel
        pipenv run twine upload dist/* --repository-url https://push.fury.io/prodperfect -p ""
